REST_APP = 'NetworkStat'

DELAY_MONITOR = 'delay_monitor'
TOPOLOGY_DATA = 'topology_data'
FLOW_MANAGER = 'flow_manager'
PORT_STATISTIC = 'port_statistic'
FLOW_STATISTIC = 'flow_statistic'


SHOW_DEBUG = True

STATS_REQUEST_INTERVAL = 3
DISCOVER_INTERVAL = 3
PROBE_PACKETLOSS_INTERVAL = 3

GRAPH_UPDATE_INTERVAL = 3

DELAY_DETECTING_INTERVAL = 3